baseURL = 'https://www.creerunjeuvideo.fr/'
theme = "hugo-book"
defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    label = "Français"
    title = "Créer un jeu vidéo"
    weight = 1

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  BookTheme = "dark"
  BookSection = "*"
  disableKinds = ["taxonomy", "term"]
