baseURL = 'https://creerunjeuvideo.fr/'
languageCode = 'fr-fr'
title = 'Créer un jeu vidéo'

theme = 'hugo-theme-relearn'

enableRobotsTXT = true

[params]
  themeVariant = ['relearn-dark', 'relearn-light']
  custom_css = ["css/custom.css"]
[outputs]
  home = ["HTML", "RSS"] # Active la barre de recherche intégrée de Relearn
